name: Two-Way Sync with ghl-api-v2-docs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Prepare sync content
        run: |
          mkdir -p /tmp/sync
          cp -r . /tmp/sync/
          rm -rf /tmp/sync/.git

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: thinkbold-solutions/union-connect-ai-pro 
          token: ${{ secrets.SYNC_TOKEN }}
          path: target

      - name: Copy files to target repo
        run: |
          rsync -av --exclude='.git' --exclude='.github' /tmp/sync/ target/
          cd target
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Automated sync from $GITHUB_REPOSITORY"
            git push origin HEAD
          fi
